# Generated by Django 2.0.1 on 2018-01-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='scores',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('player_score', models.IntegerField()),
            ],
        ),
    ]
