# Generated by Django 2.0.1 on 2018-01-22 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='scores',
            new_name='Score',
        ),
    ]
