# Generated by Django 2.0.1 on 2018-01-24 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0002_auto_20180122_1833'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ['-player_score']},
        ),
    ]
